### ISSUE TITLE
Fazer cadastro de usuário

### ISSUE THREAD

**Issue by ViniciusPuerto** [Grupo-Olimpo/E-a-Economia#3]
**Descrição**
Para que os usuário possam ter acesso a todas as funcionalidades da aplicação deve ser feito um cadastro do mesmo.

**História de Usuário Relacionada**
Como usuário quero pode me cadastrar na aplicação para que assim eu possa usar suas funcionalidades

**Requisito Relacionado**
RF01 - Permitir cadastrar/fazer login

**Épico Relacionado**
EP01 - Aplicação web de finanças pessoais

**Tasks**

- [x] Criar a Model de usuário e suas respectivas migrations.
- [x] Criar rota para sign up com sua respectivas lógicas para cração de usuário .

**Comment by codehg** [comment]
Feito e aguardando testes
