### ISSUE TITLE
Configurar ambiente para o front

### ISSUE THREAD

**Issue by ViniciusPuerto** [Grupo-Olimpo/E-a-Economia#5]
**Descrição**
Para facilitar o desenvolvimento devemos preparar o ambiente

**Tasks**

- [x] Inicializar o projeto.
- [x] Definir e aplicar uma estrutura de pastas.
- [ ] Dockerizar a aplicação.

**Comment by giovannabbottino** [comment]
Não foi adicionado o docker, mas já está feito no front
