### ISSUE TITLE
Login de usuário

### ISSUE THREAD

**Issue by ViniciusPuerto** [Grupo-Olimpo/E-a-Economia#6]
**Descrição**
Feature na qual o usuário fará a autenticação para poder usar o app

**História de Usuário Relacionada**
US01

**Requisito Relacionado**
RF01

**Épico Relacionado**
EP01

**Tasks**

- [x] Criar rota para sign in e respectivas logicas.
- [x] Fazer com que o login seja autenticável.

**Comment by codehg** [comment]
Feito e PR criado
